name: pgamit
channels:
  - defaults
  - conda-forge
dependencies:
  - python==3.10
  - basemap
  - geopy
  - h5py
  - matplotlib
  - networkx
  - numpy>=1.19.5
  - pandas
  - paramiko
  - psycopg2-binary
  - scandir>=1.6
  - scikit-learn>=1.1
  - scipy
  - tqdm
  - pytest
  - xmltodict
  - scikit-image
  - shapely
  - obspy
  - pip
  - pip:
    - country_converter
    - dispy
    - hdf5storage
    - simplekml
    - usgs-libcomcat
