version: "3.8"

services:
  backend:
    container_name: gnss-backend
    build: ./backend
    volumes:
      - ./backend:/code
      - /fs/project/gomez.124/archive_media_osu/:/code/backend_django_project/media
    ports:
      - "8000:8000"
    restart: always
