# Generated by Django 5.0.4 on 2024-09-09 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_visits_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visits',
            options={'ordering': ['-date']},
        ),
    ]
