# Generated by Django 5.0.4 on 2024-09-10 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_visits_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['last_name', 'first_name']},
        ),
    ]
