# Generated by Django 5.0.4 on 2024-09-18 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_person_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationMetaGaps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rinex_count', models.IntegerField()),
                ('record_start_date_start', models.DateTimeField(blank=True, null=True)),
                ('record_start_date_end', models.DateTimeField(blank=True, null=True)),
                ('record_end_date_start', models.DateTimeField(blank=True, null=True)),
                ('record_end_date_end', models.DateTimeField(blank=True, null=True)),
                ('station_meta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.stationmeta')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
