# Generated by Django 5.0.4 on 2024-09-18 19:36

from django.db import migrations
from django.conf import settings
import psycopg2



def connect_to_db():
    conn = psycopg2.connect(
        f'dbname={settings.DATABASES["default"]["NAME"]} user={settings.DATABASES["default"]["USER"]} password={settings.DATABASES["default"]["PASSWORD"]} host={settings.DATABASES["default"]["HOST"]} port={settings.DATABASES["default"]["PORT"]}')

    cur = conn.cursor()

    return conn, cur

def set_has_gaps_update_needed_to_true(apps, schema_editor):
    conn, cur = connect_to_db()

    query = """
    UPDATE api_stationmeta SET has_gaps_update_needed = true;
    """

    try:
        print("Executing: ", query)
        cur.execute(query)
    except Exception as e:
        print(f"Exception ocurred: {e}. Continuing...")
        conn.rollback()
    else:
        conn.commit()
    finally:
        print("---------------------------")
        cur.close()
        conn.close()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_stationmetagaps'),
    ]

    operations = [
        migrations.RunPython(set_has_gaps_update_needed_to_true)
    ]
