# Generated by Django 5.0.4 on 2024-10-31 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20241018_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitimages',
            name='name',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
