# Generated by Django 5.0.4 on 2024-11-22 18:08

from django.db import migrations


def create_station_meta(apps, schema_editor):
    Station = apps.get_model("api", "Stations")
    StationMeta = apps.get_model("api", "StationMeta")
    StationStatus = apps.get_model("api", "StationStatus")
    MonumentTypes = apps.get_model("api", "MonumentType")

    stations = Station.objects.all()

    for station in stations:
        if not StationMeta.objects.filter(station=station).exists():
            StationMeta.objects.create(
                station=station,
                status=StationStatus.objects.get(name="Active Online"),
                has_gaps=False,
                has_gaps_last_update_datetime=None,
                has_gaps_update_needed=True
            )


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20241018_1549'),
    ]

    operations = [
        migrations.RunPython(create_station_meta),
    ]
