# Generated by Django 5.0.4 on 2024-10-31 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_visitimages_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitimages',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
