# Generated by Django 5.0.4 on 2024-10-31 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_visitimages_name'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='visitimages',
            constraint=models.UniqueConstraint(fields=('visit', 'name'), name='visit_name_unique'),
        ),
    ]
