# Generated by Django 5.0.4 on 2024-10-31 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_visitimages_visit_name_unique'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='stationattachedfiles',
            constraint=models.UniqueConstraint(fields=('station', 'filename'), name='station_filename_unique'),
        ),
        migrations.AddConstraint(
            model_name='stationimages',
            constraint=models.UniqueConstraint(fields=('station', 'name'), name='station_name_unique'),
        ),
        migrations.AddConstraint(
            model_name='visitattachedfiles',
            constraint=models.UniqueConstraint(fields=('visit', 'filename'), name='visit_filename_unique'),
        ),
        migrations.AddConstraint(
            model_name='visitgnssdatafiles',
            constraint=models.UniqueConstraint(fields=('visit', 'filename'), name='visit_filename_gnss_unique'),
        ),
    ]
