# Generated by Django 5.0.4 on 2024-12-03 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20241122_1808'),
        ('api', '0015_stationattachedfiles_station_filename_unique_and_more'),
    ]

    operations = [
    ]
