# Generated by Django 5.0.4 on 2024-12-23 19:03

from django.db import migrations
from django.conf import settings
import psycopg2


def connect_to_db():
    conn = psycopg2.connect(
        f'dbname={settings.DATABASES["default"]["NAME"]} user={settings.DATABASES["default"]["USER"]} password={settings.DATABASES["default"]["PASSWORD"]} host={settings.DATABASES["default"]["HOST"]} port={settings.DATABASES["default"]["PORT"]}')

    cur = conn.cursor()

    return conn, cur


def modify_trigger_when_inserting_stations(apps, schema_editor):
    conn, cur = connect_to_db()
    query = f"""
            CREATE OR REPLACE FUNCTION create_stationmeta_from_new_station()
            RETURNS TRIGGER AS $$
            BEGIN
                IF NEW."NetworkCode" NOT LIKE '?%' THEN
                    INSERT INTO api_stationmeta (station_id, status_id, remote_access_link, has_battery, battery_description, has_communications, communications_description, comments, navigation_file, navigation_filename, has_gaps, has_gaps_last_update_datetime, has_gaps_update_needed, has_stationinfo)
                    VALUES (NEW.api_id, 
                            (SELECT id FROM api_stationstatus WHERE name = 'Active Online' LIMIT 1),
                            '', FALSE, '', FALSE, '', '', '', '',
                            FALSE, NULL, TRUE, FALSE);
                END IF;
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;
        """

    try:
        print("Executing: ", query)
        cur.execute(query)
    except Exception as e:
        print(f"Exception ocurred: {e}")
        print("Rolling back...")
        conn.rollback()
    else:
        conn.commit()
    finally:
        print("---------------------------")
    cur.close()
    conn.close()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20241223_1715'),
    ]

    operations = [
        migrations.RunPython(modify_trigger_when_inserting_stations)
    ]
