# Generated by Django 5.0.4 on 2025-01-31 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20241223_1903'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='events',
            options={'managed': False, 'ordering': ['-event_date']},
        ),
        migrations.AlterModelOptions(
            name='stationattachedfiles',
            options={'ordering': ['filename']},
        ),
        migrations.AlterModelOptions(
            name='stationimages',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='visitattachedfiles',
            options={'ordering': ['filename']},
        ),
        migrations.AlterModelOptions(
            name='visitgnssdatafiles',
            options={'ordering': ['filename']},
        ),
        migrations.AlterModelOptions(
            name='visitimages',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='person',
            name='institution',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
