# Generated by Django 5.0.4 on 2025-02-18 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_person_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationstatus',
            name='color',
            field=models.CharField(default='1', max_length=7),
        ),
        migrations.AddField(
            model_name='stationtype',
            name='icon',
            field=models.ImageField(
                default='station_type_icons/placemark_square.png', upload_to='station_type_icons/'),
        ),
    ]
