# Generated by Django 5.0.4 on 2025-02-18 14:07

from django.db import migrations, models


def define_icons_for_station_type(apps, schema_editor):
    # set icon to "station_type_icons/placemark_circle.png" for type with name 'Continuous'
    try:
        StationType = apps.get_model('api', 'StationType')
        station_type = StationType.objects.get(name='Continuous')
        station_type.icon = 'station_type_icons/placemark_circle.png'
        station_type.save()
    except StationType.DoesNotExist:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_stationstatus_color_stationtype_icon'),
    ]

    operations = [
        migrations.RunPython(define_icons_for_station_type)
    ]
