# Generated by Django 5.0.4 on 2025-02-21 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20250218_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationtype',
            name='search_icon_on_assets_folder',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='stationtype',
            name='icon',
            field=models.ImageField(upload_to='station_type_icons/'),
        ),
    ]
