# Generated by Django 5.0.4 on 2025-02-21 12:47

from django.db import migrations


def define_icons_for_station_type(apps, _):
    StationType = apps.get_model('api', 'StationType')
    try:
        station_type = StationType.objects.get(name='Campaign')
        station_type.icon = 'station_type_icons/placemark_square.png'
        station_type.search_icon_on_assets_folder = True
        station_type.save()
    except StationType.DoesNotExist:
        pass

    try:
        station_type = StationType.objects.get(name='Continuous')
        station_type.search_icon_on_assets_folder = True
        station_type.save()
    except StationType.DoesNotExist:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_stationtype_search_icon_on_assets_folder_and_more'),
    ]

    operations = [
        migrations.RunPython(define_icons_for_station_type),
    ]
