# Generated by Django 5.0.4 on 2025-02-25 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20250221_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationstatus',
            name='color',
            field=models.CharField(default='green-icon', max_length=50),
        ),
    ]
