# Generated by Django 5.0.4 on 2025-02-25 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_stationstatus_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationStatusColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(default='green-icon', max_length=50, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='stationstatus',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.stationstatuscolor'),
        ),
    ]
