# Generated by Django 5.0.4 on 2025-04-01 15:47

from django.db import migrations


def create_new_cluster_type(apps, schema_editor):
    cluster_type = apps.get_model("api", "ClusterType")
    new_cluster_type = cluster_type(name="create")
    new_cluster_type.save()


def create_station_post_permissions(apps, schema_editor):
    endpoints_cluster = apps.get_model("api", "EndPointsCluster")
    cluster_type = apps.get_model("api", "ClusterType")
    endpoint = apps.get_model("api", "Endpoint")
    resource = apps.get_model("api", "Resource")

    # READ STATIONS
    front_read_stations = endpoints_cluster(resource=resource.objects.get(name='stations'),
                                            cluster_type=cluster_type.objects.get(name="create"), role_type='FRONT')
    front_read_stations.save()
    front_read_stations.endpoints.add(
        endpoint.objects.get(path="/api/stations", method="POST"))
    front_read_stations.endpoints.add(
        endpoint.objects.get(path="/api/networks", method="GET"))


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20250225_1356'),
    ]

    operations = [
        migrations.RunPython(create_new_cluster_type),
        migrations.RunPython(create_station_post_permissions)
    ]
