# Generated by Django 5.0.4 on 2025-04-16 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20250401_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigns',
            name='default_people',
            field=models.ManyToManyField(blank=True, to='api.person'),
        ),
    ]
