# Generated by Django 5.0.4 on 2025-04-23 15:19

from django.db import migrations


def remove_gaps_status_update_related_records(apps, schema_editor):
    """This is because the validation for the 'update-gaps-status' user is made by code instead of by database records"""
    Role = apps.get_model('api', 'Role')

    # remove reference to endpoint cluster from role
    update_gaps_status_role = Role.objects.get(name='update-gaps-status')
    update_gaps_status_role.endpoints_clusters.clear()
    update_gaps_status_role.save()

    # remove endpoint cluster
    EndPointsCluster = apps.get_model('api', 'EndPointsCluster')
    EndPointsCluster.objects.get(
        resource__name='gaps-status', role_type='API').delete()
    EndPointsCluster.objects.get(
        resource__name='delete-update-gaps-status-block', role_type='API').delete()

    # remove endpoint
    Endpoint = apps.get_model('api', 'Endpoint')
    Endpoint.objects.get(
        path='/api/update-gaps-status', method='POST').delete()
    Endpoint.objects.get(
        path='/api/delete-update-gaps-status-block', method='POST').delete()

    # remove resource
    Resource = apps.get_model('api', 'Resource')
    Resource.objects.get(name='gaps-status').delete()
    Resource.objects.get(name='delete-update-gaps-status-block').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_campaigns_default_people'),
    ]

    operations = [
        migrations.RunPython(remove_gaps_status_update_related_records)
    ]
