# Generated by Django 5.0.4 on 2025-04-24 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_auto_20250423_1820'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='endpointscluster',
            name='resource_cluster_type_role_type_description_unique',
        ),
        migrations.AddConstraint(
            model_name='endpointscluster',
            constraint=models.UniqueConstraint(fields=('resource', 'cluster_type', 'role_type'), name='resource_cluster_type_role_type_unique'),
        ),
    ]
