# Generated by Django 5.0.4 on 2025-05-19 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_remove_endpointscluster_resource_cluster_type_role_type_description_unique_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sourcesservers',
            options={'managed': False, 'ordering': ['fqdn']},
        ),
    ]
