# Generated by Django 5.0.4 on 2025-07-16 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_alter_person_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitgnssdatafiles',
            name='size',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
