# Generated by Django 5.0.4 on 2025-07-17 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_visitgnssdatafiles_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='clustering_distance',
            field=models.IntegerField(null=True),
        ),
    ]
