# Generated by Django 5.0.4 on 2024-09-04 19:03

from django.db import migrations
import psycopg2
from django.conf import settings


def connect_to_db():
    conn = psycopg2.connect(
        f'dbname={settings.DATABASES["default"]["NAME"]} user={settings.DATABASES["default"]["USER"]} password={settings.DATABASES["default"]["PASSWORD"]} host={settings.DATABASES["default"]["HOST"]} port={settings.DATABASES["default"]["PORT"]}')

    cur = conn.cursor()

    return conn, cur


def set_has_stationinfo(apps, schema_editor):
    conn, cur = connect_to_db()

    query = """
    WITH stations_with_stationinfo AS ( select api_id from (select s.api_id, EXISTS (SELECT 1 FROM stationinfo si where si."NetworkCode" = s."NetworkCode" and si."StationCode" = s."StationCode") as has_stationinfo from stations s) where has_stationinfo = true)
    UPDATE api_stationmeta SET has_stationinfo = true WHERE station_id IN (SELECT * FROM stations_with_stationinfo);
    """

    try:
        print("Executing: ", query)
        cur.execute(query)
    except Exception as e:
        print(f"Exception ocurred: {e}. Continuing...")
        conn.rollback()
    else:
        conn.commit()
    finally:
        print("---------------------------")
        cur.close()
        conn.close()


def add_station_country_code_fk(apps, schema_editor):

    conn, cur = connect_to_db()

    query = "ALTER TABLE stations ADD CONSTRAINT fk_country_code FOREIGN KEY (country_code) REFERENCES api_country(three_digits_code)"

    try:
        print("Executing: ", query)
        cur.execute(query)
    except psycopg2.errors.DuplicateObject:
        print("Constraint fk_country_code already exists. Continuing...")
        conn.rollback()
    else:
        conn.commit()
    finally:
        print("---------------------------")

    cur.close()
    conn.close()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20240904_1903'),
    ]

    operations = [

        migrations.RunPython(set_has_stationinfo),
        migrations.RunPython(add_station_country_code_fk)
    ]

