# Generated by Django 5.0.4 on 2024-08-07 14:15

from django.db import migrations
import psycopg2
from django.conf import settings

def connect_to_db():
    conn = psycopg2.connect(
        f'dbname={settings.DATABASES["default"]["NAME"]} user={settings.DATABASES["default"]["USER"]} password={settings.DATABASES["default"]["PASSWORD"]} host={settings.DATABASES["default"]["HOST"]} port={settings.DATABASES["default"]["PORT"]}')

    cur = conn.cursor()

    return conn, cur

def set_has_stationinfo(apps, schema_editor):
    conn, cur = connect_to_db()

    query = """
    WITH stations_with_stationinfo AS ( select api_id from (select s.api_id, EXISTS (SELECT 1 FROM stationinfo si where si."NetworkCode" = s."NetworkCode" and si."StationCode" = s."StationCode") as has_stationinfo from stations s) where has_stationinfo = true)
    UPDATE api_stationmeta SET has_stationinfo = true WHERE station_id IN (SELECT * FROM stations_with_stationinfo);
    """

    try:
        print("Executing: ", query)
        cur.execute(query)
    except Exception as e:
        print(f"Exception ocurred: {e}. Continuing...")
        conn.rollback()
    else:
        conn.commit()
    finally:
        print("---------------------------")
        cur.close()
        conn.close()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20240807_1415'),
    ]

    operations = [

        migrations.RunPython(set_has_stationinfo),
    ]
