# Generated by Django 5.0.4 on 2024-09-06 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20240904_1903'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaigns',
            options={'ordering': ['-start_date']},
        ),
    ]
